@startuml
start

:Read batching configuration;

:Add input scope;

if (scope finished?) then (yes)
    :Log "Scope already finished";
    stop
else (no)
    if (checkpoint exists?) then (yes)
        :Read batch size from checkpoint;
    else
        :read batch size from batching configuration;
        :Create checkpoint;
    endif

    :Stream process file sequentially;

    :Read first line (headers) and store in array;

    :Log "Starting to process";

    while (more lines?) is (yes)
        :Process batch;
    endwhile (no)

endif

stop
@enduml