@startuml
legend Crow’s Foot Notation

entity project {
    * id : uuid <<generated>>
    --
    * name : character varying(255)
    * owner : character varying(255)
    * created_date : timestamp(6) without time zone
    last_updated_date : timestamp(6) without time zone
}

entity scope {
    * id : uuid <<generated>>
    --
    * key : character varying(255)
    * created_date : timestamp(6) without time zone
    * finished : boolean
    * external : boolean
    * project_id : uuid <<FK>>
}

entity item {
    * id : uuid <<generated>>
    --
    * status : character varying(255)
    properties : jsonb
    * scope_id : uuid <<FK>>
}

entity checkpoint {
    * id : uuid <<generated>>
    --
    * batch_size : integer
    * total_batches: bigint
    * scope_id : uuid <<FK>>
}

entity checkpoint_batches {
    * id : uuid <<generated>>
    --
    * batch_index : bigint
    * checkpoint_id : uuid <<FK>>
}

entity host {
    * id : uuid <<generated>>
    --
    * name : character varying(255)
    * url : character varying(255)
}

entity database {
    * id : uuid <<generated>>
    --
    * name : character varying(255)
    * host_id : uuid <<FK>>
}

project ||..|{ scope
scope ||..|{ item

scope ||.|| checkpoint

checkpoint ||..|{ checkpoint_batches

host ||..|{ database

host -[hidden]> scope

@enduml