@startuml
legend Crow’s Foot Notation

entity project {
    * id : UUID <<generated>>
    --
    * name : text
    * owner : text
    * created : date
    last_updated : date
}

entity scope {
    * id : UUID <<generated>>
    --
    * key : text
    * created : date
    * finished : boolean
    * external : boolean
    * project_id : UUID <<FK>>
}

entity item {
    * id : UUID <<generated>>
    --
    * status : text
    properties : text
    * scope_id : UUID <<FK>>
}

entity checkpoint {
    * id : UUID <<generated>>
    --
    * batch_size : integer
    * total_batches: long
    * scope_id : UUID <<PK>>
}

entity checkpoint_batches {
    * id : UUID <<generated>>
    --
    * batch_index : long
    * checkpoint_id : UUID <<FK>>
}

entity host {
    * id : UUID <<generated>>
    --
    * name : text
    * url : text
}

entity database {
    * id : UUID <<generated>>
    --
    * name : text
    * host_id : UUID <<FK>>
}

project ||..|{ scope
scope ||..|{ item

scope ||.|| checkpoint

checkpoint ||..|{ checkpoint_batches

host ||..|{ database

host -[hidden]> scope

@enduml